name: Test processes

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ">=3.10"

      # 3️⃣ Ensure Docker is available
      - name: Check Docker
        run: |
          if ! command -v docker &> /dev/null
          then
            echo "Docker could not be found!"
            exit 1
          fi
          docker --version

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.JAWM_BIOINFORMATICS_KEY }}

      - name: Add GitHub to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Install jawm
        run: |
          python -m pip install --upgrade pip
          pip install git+ssh://git@github.com/mpg-age-bioinformatics/jawm.git --user

      - name: Download data
        run: |
          mkdir test/test-input
          while read -r _ filename url _ ;
            do
              if [ ! -f "./test/test-input/${filename}" ]; then
                wget -O "./test/test-input/${filename}" "$url"
              fi
          done < ./test/data.txt
          awk '{print $1, "./test/test-input/"$2}' ./test/data.txt | md5sum -c -

      - name: Run jawm
        run: |
          for py in $(ls *.py) ; 
            do 
              tag=${py%.py}
              for parameters_yaml in $(ls ./test/${tag}${suffix}.*.yaml ) ; 
                do
                  printf "\n\n\njawm ${py} -p ${parameters_yaml} --hash hash.yaml\n\n\n"
                  jawm ${py} -p ${parameters_yaml} --hash hash.yaml
              done
          done

      - name: Succeeded
        if: success()
        run: echo "✅ test.py succeeded!" 

      - name: Slack Failure Notification
        if: failure() # skip during local actions testing
        run: |
          echo "❌ Job failed!" && \
          generate_post_data()
          {
            cat << EOF
          {
            "text": "${GITHUB_REPOSITORY##*/}@$(echo $GITHUB_SHA | cut -c 1-8) test FAILED"
          }
          EOF
          } 
          curl -H "Content-Type: application/json" -X POST -d "$(generate_post_data)" ${{ secrets.SLACK_JAWM_WEBHOOK }}

# from the jawm_fastqc folder
# act -s JAWM_BIOINFORMATICS_KEY="$(cat ~/.ssh/jawm)"